### ISSUE TITLE
THANK YOU - Request to add to official examples.

### ISSUE THREAD

**Issue by c-git** [woelper/egui_pick_file#1]
I've been struggling to try to get this to work for a while (only a few hours but I didn't like any of the solutions I could find). I want to play more with what you've done but would you be ok with me trying to get it added to the official examples on egui so other people can find it? The one that is there now is fine but only works for native. I'm not necessarily saying to replace the current one but rather to add this one because it also works in the browser.

Let me know what you think please.

**Comment by c-git** [comment]
PS. For the async local part I'd want to maybe feature flag it as ppl may not know how to use the different executors and would appreciate an example. At least for [tokio](https://docs.rs/tokio/latest/tokio/#) and [async_std](https://docs.rs/async-std/latest/async_std/#)

**Comment by woelper** [comment]
You are welcome, and yes - please go ahead and add it to the examples, I think this makes sense. I can assure you I spent way to many hours figuring this out myself.

**Comment by c-git** [comment]
Thank you I will surely do that because the next person may not be as lucky as me to find yours.

**Comment by c-git** [comment]
Created a discussion on the repo to see if they would be willing to include the example https://github.com/emilk/egui/discussions/3783

**Comment by c-git** [comment]
> It is a bit cumbersome to have freestanding examples that compile and run as wasm (or at least it is currently). Therefore I suggest you instead improve https://github.com/woelper/egui_pick_file and we can link to that as an example from the main `egui` repo

_Originally posted by @emilk in https://github.com/emilk/egui/discussions/3783#discussioncomment-8044984_

So @woelper if it's ok with you I'll make the changes I was suggesting in https://github.com/woelper/egui_pick_file/issues/3 and then add a link from the egui docs to here. Let me know if that is ok with you please.

**Comment by woelper** [comment]
Yes totally ok! You rock, and thanks for all your effort!

**Comment by c-git** [comment]
Ok great thanks, will do a PR to make the changes I was talking about. Will probably do a few smaller PRs with the different parts. Let me know if it's too many and I'll just do one big one if you'd prefer that. Right now my intention is to make them cumulative so if you do them in order each should be small or you can just do the last one and it will have included all the others. Will re-base as need if a PR has to change so don't worry about that.

**Comment by c-git** [comment]
BTW thanks for making the changes https://github.com/woelper/egui_pick_file/issues/3, I think I was on track to over engineer this.

**Comment by c-git** [comment]
PS. I've updated the [discussion](https://github.com/emilk/egui/discussions/3783) as I'm having second thoughts about how discoverable it will be if we put it in the readme. My usual go to is the web_demo then the examples then I start looking elsewhere. I don't often re-read the readme.

**Comment by c-git** [comment]
This [line of code](https://github.com/woelper/egui_pick_file/blob/f6e9cc7409db2ba7a55acec32efa5ec3b1dfadb0/src/app.rs#L69) has always bothered me and I've been looking for a way to abstract all of that out of the program and found https://github.com/EmbarkStudios/poll-promise . I was trying to replace executor part with this crate and in the process was doing a Cargo.toml and I noticed it includes tokio but it is not used. So I'm going to do a few small PRs to clean up the `Cargo.toml` and use poll-promise. I need it for me so I'll do the PR anyway and if you don't want it it's fine you can close the PR as needed. I am just doing this update to the issue to find out if there is a reason the unused crates are in the `Cargo.toml`

**Comment by c-git** [comment]
After having tried I have decided that this would add too much complexity to this example. I was hoping it would have been simpler. I think it's easier to go from you code to another solution that to introduce so much complexity and leave the user wondering what is relevant to this example.

**Comment by c-git** [comment]
Ok hopefully the PR for the addition to the readme will get merged I don't think we need to keep this issue open anymore so I'm going to close it.
