### ISSUE TITLE
Change to Read/Write?

### ISSUE THREAD

**Issue by c-git** [woelper/egui_pick_file#3]
Hi,

Thank you so much again for this. You don't know how much you've helped.

For my use case I need both upload and download of files. Would you want me to submit a PR for a version that can do both upload and download? I'm somewhat reluctant because I got from what you did to saving pretty easily and simplicity is not to be ignored but I wonder if everyone would be able to make the jump as easily hence why I'm wondering if I should. I also think a github pages version would be good so people can try without downloading or compiling. Can do a separate PR for that if that is something you are interested in.

**Comment by woelper** [comment]
Hi!
Don't worry - just add the example as you see fit! Fantastic idea about the github pages version!

**Comment by c-git** [comment]
Ok thanks, would you want to update this one to support read/write as well or just make the example and submit to them direct?

**Comment by woelper** [comment]
I added write support (made a button for it). Also github pages is now active.

**Comment by c-git** [comment]
Looks great, thank you.
